name: Deploy to EC2

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Add EC2 host to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan 3.145.106.40 >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        env:
          EC2_HOST: 3.145.106.40
          EC2_USER: ubuntu
        run: |
          cat > deploy.sh << 'EOL'
          set -e
          cd FlyBy
          git pull origin main
          sudo docker buildx bake -f docker-bake.hcl
          sudo docker compose up -d --build
          sudo docker image prune -f
          EOL

          scp deploy.sh ubuntu@3.145.106.40:~/deploy.sh

          ssh ubuntu@3.145.106.40 "chmod +x ~/deploy.sh && ~/deploy.sh"
