FROM python:3.10-slim

RUN apt-get update && apt-get install -y \
    ffmpeg \
    python3-tk \
    tk-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .

COPY . .

RUN sed -i 's/matplotlib.use("TkAgg")/matplotlib.use("Agg")/g' sort.py

RUN pip3 install torch torchvision --index-url https://download.pytorch.org/whl/cpu
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

CMD ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]